import React, { useEffect, useState } from 'react';
import { AGENT_TRACKS } from '../lib/agent-tracks';
import { listIntakes, parseIntake, saveIntake, validateIntake, type Intake, type DataKind } from '../services/dataIntake';
import { logConnection } from '../services/connectionLog';
export default function DataIntake() {
  const [kind, setKind] = useState<DataKind>('business'), [draft, setDraft] = useState<Intake>(), [items, setItems] = useState<Intake[]>([]), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [dragging, setDragging] = useState(false);
  const [queuedFiles, setQueuedFiles] = useState<File[]>([]);
  const chooseFiles = (files: File[]) => { if (busy || !files.length) return; setQueuedFiles(files.slice(1)); void preview(files[0]); };
  const nextFile = () => { const [next, ...rest] = queuedFiles; setQueuedFiles(rest); if (next) void preview(next); else { setDraft(undefined); setError(''); } };
  const refresh = () => listIntakes().then(setItems).catch(() => setError('Local data storage unavailable.'));
  useEffect(() => { void refresh(); }, []);
  const issues = draft ? validateIntake(draft.rows, kind, draft.mapping) : [];
  const columns = draft ? [...new Set(draft.rows.slice(0, 20).flatMap(Object.keys))] : [];
  const button = 'rounded-xl border border-cyan-400/40 px-4 py-3 text-sm text-cyan-200 disabled:opacity-40';
  const preview = async (file?: File) => {
    if (!file) return; setBusy(true); setError(''); setDraft(undefined);
    try { if (file.size > 5 * 1024 * 1024) throw new Error('First version supports files up to 5 MB.'); const original = await file.text(); const rows = parseIntake(file.name, original); if (rows.length > 10000) throw new Error('First version supports up to 10,000 records per import.'); const hash = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(original)))).map(b => b.toString(16).padStart(2, '0')).join(''); setDraft({ id: crypto.randomUUID(), name: file.name, kind, original, hash, rows, issues: [], agents: [], mapping: {}, importedAt: '' }); } catch(e) { setError(e instanceof Error ? e.message : 'File could not be read.'); } finally { setBusy(false); }
  };
  return <section className="space-y-6 pb-12" aria-label="Data Intake"><header><h1 className="text-3xl font-bold text-white">Data Intake</h1><p className="mt-3 text-slate-300">Choose a source → preview → validate → import → assign. Trading, business, personal and chat records share one process.</p><p className="mt-2 text-sm text-slate-400">Files stay in this browser’s local database. Original text and provenance are preserved. No automatic cloud sync or model calls.</p></header>
    <label className="block text-slate-200">Data purpose<select aria-label="Data purpose" className="ml-3 rounded-xl bg-slate-900 p-3" value={kind} onChange={e => { setKind(e.target.value as DataKind); if (draft) setDraft({ ...draft, agents: [] }); }}><option value="trading">Trading research</option><option value="business">Business</option><option value="personal">Personal</option><option value="chat">Chat records</option></select></label>
    <div role="region" aria-label="File drop zone" onDragOver={e => { e.preventDefault(); if (!busy) setDragging(true); }} onDragLeave={e => { if (!e.currentTarget.contains(e.relatedTarget as Node | null)) setDragging(false); }} onDrop={e => { e.preventDefault(); setDragging(false); chooseFiles(Array.from(e.dataTransfer.files)); }} className={`rounded-2xl border-2 border-dashed p-7 ${dragging ? 'border-cyan-300 bg-cyan-500/15' : 'border-slate-600 bg-slate-900/40'}`}><h2 className="text-lg font-bold text-white">Drop files here or choose files</h2><p className="mt-2 text-sm text-slate-300">CSV, JSON, JSONL, TXT, MD · 5 MB per file · review each file before import</p><label className="mt-4 block text-slate-200">Choose local files<input aria-label="Choose intake file" type="file" multiple disabled={busy} accept=".csv,.json,.jsonl,.txt,.md" className="mt-3 block" onChange={e => { chooseFiles(Array.from(e.target.files || [])); e.target.value = ''; }}/></label><p role="status" className="mt-3 text-sm text-cyan-200">{busy ? 'Reading file…' : queuedFiles.length ? `${queuedFiles.length} more files queued for review` : 'Files are not imported until you approve the preview.'}</p>{queuedFiles.length > 0 && <button className={button + ' mt-3'} disabled={busy} onClick={nextFile}>Review next file</button>}</div>
    <details className="rounded-xl border border-violet-400/30 p-5"><summary className="cursor-pointer font-semibold text-violet-200">How to use memory and your knowledge base</summary><div className="mt-4 space-y-3 text-sm text-slate-300"><p><strong>1. Keep originals:</strong> Intake preserves the source and fingerprint. This is local browser storage, not a backed-up knowledge base.</p><p><strong>2. Knowledge base:</strong> Index reviewed documents and chat messages as chunks with source ID, version, speaker, timestamp and agent scope. Retrieve relevant chunks with citations; do not send a whole archive as a prompt.</p><p><strong>3. Memory:</strong> Retain reviewed preferences, decisions, lessons and concise summaries. Keep their source references. Chat exports are evidence, not automatically true facts or agent instructions.</p><p><strong>Trading:</strong> Keep quotes, trades and time series in structured storage for time-filtered queries. Embed strategy notes and explanations; embeddings do not replace numerical data or settlement checks.</p><p><strong>Business and personal:</strong> Separate knowledge collections and private scopes. Redact credentials and unnecessary personal details before embedding; choose an embedding provider and storage destination explicitly.</p><p className="text-amber-200">Current intake supports local import and agent-selected excerpts. It does not yet embed or publish imports to Hindsight, Honcho or a shared KB. Assignment is a source selection, not memory indexing.</p></div></details>
    {draft && <div className="space-y-4 rounded-2xl border border-cyan-400/30 p-5"><h2 className="text-xl font-bold text-white">Preview · {draft.name}</h2><p className="text-slate-300">{draft.rows.length} records · Original retained · SHA-256 fingerprint</p>{kind === 'trading' && <div className="grid gap-3 sm:grid-cols-3">{['timestamp', 'instrument', 'price'].map(field => <label key={field} className="text-slate-300">{field}<select aria-label={`Map ${field}`} value={draft.mapping[field] || ''} onChange={e => setDraft({ ...draft, mapping: { ...draft.mapping, [field]: e.target.value } })} className="block w-full rounded-lg bg-slate-900 p-2"><option value="">Choose column</option>{columns.map(c => <option key={c}>{c}</option>)}</select></label>)}</div>}<pre className="max-h-64 overflow-auto whitespace-pre-wrap rounded-xl bg-slate-900 p-4 text-xs text-slate-300">{JSON.stringify(draft.rows.slice(0, 3), null, 2).slice(0, 9000)}</pre><div className="text-sm text-amber-200">{issues.length ? issues.map(issue => <p key={issue}>{issue}</p>) : <p>Basic validation passed. Accuracy and source rights require your review.</p>}</div><p className="text-sm text-slate-400">Imports start private with no agent assignments. Duplicate files are blocked; duplicate rows are retained and flagged.</p><button disabled={busy || !draft.rows.length} className={button} onClick={async () => { setBusy(true); setError(''); try { const existing = await listIntakes(); if (existing.some(i => i.hash === draft.hash && i.kind === kind)) throw new Error('This file is already imported for this purpose.'); await saveIntake({ ...draft, kind, issues, importedAt: new Date().toISOString() }); logConnection('Data intake', 'imported', `${kind} · ${draft.rows.length} records · ${issues.length} review flags`); setDraft(undefined); await refresh(); } catch(e) { setError(e instanceof Error ? e.message : 'Import failed.'); } finally { setBusy(false); } }}>Import reviewed data locally</button></div>}
    {error && <p role="alert" className="text-amber-200">{error}</p>}<h2 className="text-xl font-bold text-white">Your sources · {items.length}</h2>{items.map(item => <article key={item.id} className="space-y-3 rounded-xl border border-slate-700 p-5"><h3 className="font-bold text-white">{item.name}</h3><p className="text-sm text-slate-300">{item.kind} · {item.rows.length} records · {item.issues.length ? 'Needs review' : 'Ready for selection'} · {new Date(item.importedAt).toLocaleString()}</p>{item.issues.map(i => <p key={i} className="text-xs text-amber-200">{i}</p>)}<details><summary className="cursor-pointer text-cyan-200">Assign to agents · {item.agents.length} selected</summary><p className="my-3 text-xs text-slate-400">Assignment makes this source selectable in that agent’s task workspace. You still choose it explicitly before submitting a task to a provider.</p>{AGENT_TRACKS.map(a => <label key={a.id} className="block py-1 text-sm text-slate-300"><input type="checkbox" checked={item.agents.includes(a.id)} onChange={async e => { const next = { ...item, agents: e.target.checked ? [...item.agents, a.id] : item.agents.filter(id => id !== a.id) }; try { await saveIntake(next); await refresh(); logConnection('Data intake', 'assignment-updated', `${item.kind} · ${next.agents.length} agent assignments`); } catch { setError('Could not save assignments.'); } }}/> {a.label}</label>)}</details><button className={button} onClick={async () => { try { await saveIntake({ ...item, agents: [] }); await refresh(); logConnection('Data intake', 'unassigned', 'Source removed from all agent selections; original retained'); } catch { setError('Could not remove assignments.'); } }}>Remove from all agent selections</button></article>)}
  </section>;
}
