import React, { useEffect, useState } from 'react';
const field = 'w-full rounded-xl border border-slate-700 bg-[#071124] px-3 py-2 text-sm text-slate-100';
const button = 'rounded-xl border border-slate-600 px-4 py-2 text-sm text-slate-100 disabled:opacity-40';
export default function GatewayPolicies() {
  const [status, setStatus] = useState<any>(), [routes, setRoutes] = useState<any[]>([]), [route, setRoute] = useState('');
  const [name, setName] = useState('Local text agents'), [operator, setOperator] = useState(true), [enabled, setEnabled] = useState(false), [approve, setApprove] = useState(false);
  const [input, setInput] = useState(16000), [output, setOutput] = useState(512), [rate, setRate] = useState(5), [calls, setCalls] = useState(100), [cap, setCap] = useState(1), [reserve, setReserve] = useState(0.01);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState('');
  async function api(path: string, method = 'GET', body?: any) { const r = await fetch('/api/inference' + path, { method, headers: { 'X-Quanta-Client': 'local-ui', ...(body ? { 'Content-Type': 'application/json' } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) }); const d = await r.json(); if (!r.ok) throw new Error(d.error?.message || 'Gateway policy unavailable'); return d; }
  async function refresh() { setStatus(await api('/gateway-policy')); const d = await api('/providers'); setRoutes(d.connections.filter((c: any) => c.model && (c.id === 'local' || c.hasKey))); }
  useEffect(() => { void refresh().catch(e => setError(e.message)); }, []);
  async function act(fn: () => Promise<void>) { setBusy(true); setError(''); setMessage(''); try { await fn(); } catch(e: any) { setError(e.message); } finally { setBusy(false); } }
  const number = (label: string, value: number, set: (v: number) => void) => <label className="block text-sm text-slate-300">{label}<input type="number" className={field} value={value} disabled={busy} onChange={e => set(Number(e.target.value))} /></label>;
  return <section aria-label="Gateway access policies" className="space-y-3 rounded-2xl border border-slate-700 p-5"><h3 className="font-semibold text-white">Gateway access policies</h3><p className="text-sm text-slate-300">General text-agent inference requires an enabled policy. External clients receive separate revocable keys pinned to one saved provider/model. Broad legacy keys are rejected. Tools, plugins and streaming are disabled on these scoped routes.</p>
    <button className={button} disabled={busy} onClick={() => act(refresh)}>Refresh saved routes and policies</button>
    <label className="block text-sm text-slate-300">Client name<input className={field} value={name} disabled={busy} onChange={e => setName(e.target.value)} /></label>
    <label className="block text-sm text-slate-300">Allowed route<select className={field} value={route} disabled={busy} onChange={e => { setRoute(e.target.value); setEnabled(false); setApprove(false); }}><option value="">Choose a configured provider/model</option>{routes.map(r => <option key={r.id} value={`${r.id}/${r.model}`}>{r.id} / {r.model}</option>)}</select></label>
    <label className="flex gap-2 text-sm text-slate-300"><input type="checkbox" checked={operator} disabled={busy} onChange={e => setOperator(e.target.checked)} /> Policy for local Quanta text agents (uncheck to create an external client)</label>
    <div className="grid gap-3 md:grid-cols-2">{number('Maximum input bytes',input,setInput)}{number('Maximum output tokens',output,setOutput)}{number('Requests per minute',rate,setRate)}{number('Monthly call limit',calls,setCalls)}{number('Monthly spending reservation cap (USD)',cap,setCap)}{number('Conservative reservation per cloud call (USD)',reserve,setReserve)}</div>
    <p className="text-xs text-slate-400">Calls reserve the configured amount before submission and retain it on failure or restart. These are hard local call/reservation limits, not an invoice guarantee. Set the per-call estimate conservatively for the input/output bounds and enforce spending caps with the provider. One active call per client.</p>
    <label className="flex gap-2 text-sm text-slate-300"><input type="checkbox" checked={approve} disabled={busy} onChange={e => setApprove(e.target.checked)} /> Approve cloud data export and spending reservations for this exact route</label>
    <label className="flex gap-2 text-sm text-slate-300"><input type="checkbox" checked={enabled} disabled={busy} onChange={e => setEnabled(e.target.checked)} /> Enable this policy</label>
    <button className={button} disabled={busy || !route} onClick={() => act(async () => { const separator = route.indexOf('/'); const d = await api(operator ? '/gateway-policy/operator' : '/gateway-policy/clients', operator ? 'PUT' : 'POST', { provider: route.slice(0,separator), model: route.slice(separator+1), name, enabled, approveCloud: approve, maxInputBytes:input,maxOutputTokens:output,requestsPerMinute:rate,monthlyCalls:calls,monthlyCapUsd:cap,reservePerCallUsd:reserve }); if (d.key) { await navigator.clipboard.writeText(d.key); setMessage('Scoped client created; its credential was copied to the clipboard and encrypted locally.'); } else setMessage('Local agent policy saved. No model request sent.'); await refresh(); })}>Save scoped policy</button>
    {status?.clients.map((c: any) => <div key={c.id} className="rounded-xl border border-slate-700 p-3 text-sm text-slate-300"><p>{c.name} · {c.route} · {c.enabled ? 'Enabled' : 'Disabled'} · {c.calls}/{c.monthlyCalls} calls · ${c.reservedUsd.toFixed(4)} reserved this month</p><button className={button} disabled={busy || !c.enabled} onClick={() => act(async () => { await api(`/gateway-policy/clients/${c.id}/revoke`,'POST'); await refresh(); setMessage('Client disabled; future requests are denied.'); })}>Disable / revoke</button></div>)}
    <div aria-live="polite">{busy && <p className="text-sm text-cyan-300">Saving policy…</p>}{message && <p className="text-sm text-emerald-300">{message}</p>}{error && <p className="text-sm text-rose-300" role="alert">{error}</p>}</div>
  </section>;
}
