import React, { useEffect, useState } from 'react';
const field = 'w-full rounded-xl border border-slate-700 bg-[#071124] px-3 py-2 text-sm text-slate-100';
const button = 'rounded-xl border border-slate-600 px-4 py-2 text-sm text-slate-100 disabled:opacity-40';
type Status = { configured: boolean; connected: boolean; projectId: string; model: string; redirectUri: string };
export default function GoogleOAuthCard() {
  const [status, setStatus] = useState<Status>(), [clientId, setClientId] = useState(''), [clientSecret, setClientSecret] = useState(''), [project, setProject] = useState('');
  const [models, setModels] = useState<{ id: string; name: string }[]>([]), [model, setModel] = useState('');
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('');
  async function api(path: string, method = 'GET', body?: unknown) { const r = await fetch('/api/google-oauth' + path, { method, headers: { 'X-Quanta-Client': 'local-ui', ...(body ? { 'Content-Type': 'application/json' } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) }); if (!r.headers.get('content-type')?.includes('application/json')) throw new Error('Quanta backend unavailable. Start the full local server to connect Google.'); const d = await r.json(); if (!r.ok) throw new Error(d.error?.message || 'Google API connection unavailable.'); return d; }
  async function refresh() { const s = await api('/status'); setStatus(s); setClientId(s.clientId); setProject(s.projectId); setModel(s.model); setModels([]); if (s.connected) setModels((await api('/models')).models); }
  useEffect(() => { void refresh().catch(e => setError(e.message)); }, []);
  async function act(fn: () => Promise<void>) { setBusy(true); setError(''); setMessage(''); try { await fn(); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }
  return <section className="space-y-3 rounded-2xl border border-slate-700 p-5" aria-label="Google API OAuth connection">
    <h3 className="font-semibold text-white">Google · Gemini API OAuth</h3>
    <p className="text-sm text-slate-300">Use your own Google Cloud project and Desktop OAuth client. Enable the Generative Language API and add your Google account as a test user if needed. API quotas and billing apply; this does not connect a Gemini app subscription or your Gmail inbox.</p>
    <a className="text-sm text-cyan-300" href="https://ai.google.dev/gemini-api/docs/oauth" target="_blank" rel="noreferrer">Google OAuth setup instructions</a>
    <p className="text-sm text-slate-300">{status?.connected ? 'Google API authorized' : status?.configured ? 'OAuth client saved · awaiting sign-in' : 'OAuth client required'}</p>
    <label className="block text-sm text-slate-300">Google Cloud project ID<input className={field} value={project} disabled={busy} onChange={e => setProject(e.target.value)} /></label>
    <label className="block text-sm text-slate-300">Desktop OAuth client ID<input className={field} value={clientId} disabled={busy} onChange={e => setClientId(e.target.value)} placeholder="…apps.googleusercontent.com" /></label>
    <label className="block text-sm text-slate-300">OAuth client secret<input className={field} type="password" autoComplete="off" value={clientSecret} disabled={busy} onChange={e => setClientSecret(e.target.value)} placeholder={status?.configured ? 'Leave blank to retain the saved secret' : 'Client secret from your Desktop OAuth client'} /></label>
    <div className="flex flex-wrap gap-3"><button className={button} disabled={busy || !clientId || !project} onClick={() => act(async () => { await api('/client', 'PUT', { clientId, clientSecret, projectId: project }); setClientSecret(''); await refresh(); setMessage('OAuth client encrypted locally.'); })}>Save Google OAuth client</button><button className={button} disabled={busy || !status?.configured} onClick={() => act(async () => { window.location.assign((await api('/authorize', 'POST')).authorizeUrl); })}>Continue with Google</button></div>
    {status?.connected && <><label className="block text-sm text-slate-300">Google API model<select className={field} value={model} disabled={busy} onChange={e => setModel(e.target.value)}><option value="">Choose an available model</option>{models.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><div className="flex flex-wrap gap-3"><button className={button} disabled={busy || !model} onClick={() => act(async () => { await api('/model', 'PUT', { model }); await refresh(); setMessage('Google model saved for explicit connection tests.'); })}>Save Google model</button><button className={button} disabled={busy || !status.model} onClick={() => act(async () => setMessage((await api('/test', 'POST')).text))}>Send Google API connection test</button><button className={button} disabled={busy} onClick={() => act(async () => { const d = await api('/disconnect', 'POST'); await refresh(); setMessage(d.remoteRevocationConfirmed ? 'Google session revoked.' : 'Disconnected locally; remote revocation was not confirmed.'); })}>Disconnect Google</button></div><p className="text-xs text-slate-400">OAuth is available for catalog discovery and explicit tests. Existing agent defaults and Business workers keep their selected routes.</p></>}
    <div aria-live="polite">{busy && <p className="text-sm text-cyan-300">Checking Google connection…</p>}{error && <p className="text-sm text-rose-300" role="alert">{error}</p>}{message && <p className="text-sm text-emerald-300">{message}</p>}</div>
  </section>;
}
