import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

export default function OpenDotsAgent() {
  const [status, setStatus] = useState<any>(null);
  useEffect(() => { const controller = new AbortController(); fetch('/api/opendots/status', { headers: { 'X-Quanta-Client': 'local-ui' }, signal: controller.signal }).then(response => response.json()).then(setStatus).catch(error => { if (!controller.signal.aborted) setStatus({ error: error.message }); }); return () => controller.abort(); }, []);
  return <div className="p-6 sm:p-10 space-y-6"><header className="rounded-3xl border border-orange-400/30 bg-gradient-to-br from-blue-950 via-slate-950 to-cyan-950 p-8"><p className="text-orange-300 uppercase tracking-widest text-xs">Persistent specialist coworkers</p><h1 className="mt-3 text-4xl font-bold text-white">Quanta OpenDots</h1><p className="mt-4 text-slate-300">Name your Dots, assign roles, and give each a dedicated Space. Optional computers preserve a separate browser and workspace for each Dot.</p><div className="mt-5 flex flex-wrap gap-3"><a href="http://127.0.0.1:4310" target="_blank" rel="noreferrer" className="rounded-xl bg-gradient-to-r from-cyan-600 to-blue-600 px-5 py-3 text-white">Open local OpenDots</a><Link to="/agents" className="rounded-xl border border-orange-400/40 px-5 py-3 text-orange-200">Agent directory</Link></div></header>
    <section className="rounded-2xl border border-slate-700 bg-slate-950 p-6"><h2 className="text-xl font-bold text-cyan-200">Local runtime</h2><p role="status" className="mt-3 text-slate-300">{!status ? 'Checking…' : status.reachable ? `Connected · ${status.count} Dots` : status.error || 'Not running'}</p>{status?.setup?.missing?.length > 0 && <p className="mt-3 text-orange-200">Setup required: {status.setup.missing.join(', ')}</p>}<p className="mt-4 text-sm text-slate-400">Sign in to the separate local console using OWNER_TOKEN from C:\QuantaOpenDots\.env. Owner and provider keys stay on the server. A valid Intelligence project and model provider are required for conversations.</p></section>
    <div className="grid gap-4 md:grid-cols-3">{[['Local Docker', 'Per-Dot isolation through the OpenDots supervisor. Browser, files and shell begin disabled. Starting the supervisor grants it access to the Docker engine.'], ['Cloud session', 'Run OpenDots and its computer supervisor on your infrastructure. Configure OPENDOTS_CLOUD_URL and OPENDOTS_CLOUD_OWNER_TOKEN only in the Quanta server environment.'], ['Memory & handoffs', 'OpenDots Spaces are separate from Open House private and master KBs. Group conversations and automatic delegation are not provided by this upstream version.']].map(([title, text]) => <section key={title} className="rounded-2xl border border-blue-400/20 p-6"><h2 className="font-bold text-white">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p></section>)}</div>
  </div>;
}
