import React, { useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { workzoneService as api } from '../services/workzoneService';
import { WORKER_HARNESSES, type OperatorWorkZone, type WorkZone } from '../lib/workzone-contract';

const input = 'w-full rounded-xl bg-slate-950 border border-slate-700 p-3 text-sm text-white';
const button = 'rounded-xl bg-gradient-to-r from-orange-500 to-amber-400 px-5 py-3 text-slate-950 font-bold disabled:opacity-40';
const panel = 'rounded-2xl border border-slate-800 bg-slate-900/60 p-5';
const templates = { build: [['Work Lead','Coordinate briefs, assign work and request human review.'],['Builder','Build scoped changes using approved tools and preserve evidence.'],['Quality Reviewer','Review deliverables, security and acceptance criteria.']], trade: [['Desk Lead','Coordinate SME research, preserve dissent and request operator review.'],['Market Analyst','Assess source-backed market evidence and timestamp assumptions.'],['Bull Researcher','Develop the strongest evidence-backed positive thesis.'],['Bear Researcher','Challenge the thesis and identify missing evidence.'],['Risk Reviewer','Review sizing, uncertainty and downside; no financial execution.']] };
export default function OperatorWorkZone({ zone = 'build' }: { zone?: WorkZone }) {
  const location = useLocation();
  const candidate = location.state?.onboard;
  const identity = candidate && typeof candidate.name === 'string' && typeof candidate.role === 'string' ? { name: candidate.name.slice(0,80), role: candidate.role.slice(0,1500) } : null;
  const [state,setState] = useState<OperatorWorkZone|null>(null), [error,setError] = useState(''), [busy,setBusy] = useState(false), [notice,setNotice] = useState('');
  const [tab,setTab] = useState(identity ? 'Onboarding' : 'Workboard');
  const [worker,setWorker] = useState({name:identity?.name||'',role:identity?.role||'',adapterType:'http',reportsTo:'',budgetMonthlyCents:0});
  const [task,setTask] = useState({title:'',description:'',agentId:''});
  const [review,setReview] = useState({agentId:'',caseName:'',skillVersion:'',artifact:'',verdict:'revise',notes:''});
  const [note,setNote] = useState({agentId:'master',title:'',text:'',source:''});
  async function refresh() { try { setState(await api.state(zone)); setError(''); } catch(e) {setError((e as Error).message);} }
  useEffect(()=>{setState(null); void refresh(); const timer=window.setInterval(()=>void refresh(),30000); return ()=>window.clearInterval(timer);},[zone]);
  async function act(fn:()=>Promise<unknown>,message:string) { setBusy(true);setNotice(''); try { const result = await fn();setNotice(result && typeof result === 'object' && 'summary' in result && typeof result.summary === 'string' ? result.summary : message);await refresh(); } catch(e) {setError((e as Error).message);} finally {setBusy(false);} }
  const agents=state?.agents||[];
  const options=<><option value="">Human operator / unassigned</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</>;
  const workerOptions=<><option value="">Select a worker</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</>;
  function exportWorkspace(){if(!state)return; const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`quanta-${zone}-workspace.json`;a.click();URL.revokeObjectURL(url);}
  return <div className="space-y-6 pb-12">
    <header className="relative overflow-hidden rounded-3xl border border-orange-500/40 bg-gradient-to-br from-indigo-950 via-slate-950 to-cyan-950 p-8 md:p-12">
      <p className="text-orange-400 uppercase text-xs font-bold tracking-[.3em]">{zone==='trade'?'QuantaTrade digital workers':'Quanta · Operator Work Zone'}</p>
      <h1 className="text-4xl md:text-5xl font-bold mt-4">Give every worker a place<br/><span className="text-cyan-300">to build, learn and deliver.</span></h1>
      <p className="text-slate-300 max-w-2xl mt-5">One operator organization. Named workers, explicit reporting lines, assigned harnesses and reviewed work. Private worker knowledge plus a deliberate shared master KB.</p>
      <div className="flex gap-3 flex-wrap mt-6"><a className={button} href={state?.consoleUrl||'http://localhost:3210'} target="_blank" rel="noreferrer">Open Paperclip console ↗</a><button className="px-4 py-3 rounded-xl border border-slate-700 text-sm" disabled={busy} onClick={refresh}>Refresh workspace</button><button className="px-4 py-3 border border-cyan-800 rounded-xl text-sm" disabled={busy||!state?.company||state.scope!=='local-operator'} onClick={()=>act(()=>api.console(zone),'Console connected. Open the Paperclip console above.')}>Connect console session</button><a className="px-5 py-3 border border-cyan-800 rounded-xl" href={zone==='trade'?'#/work-zone':'#/quantatrade'}>{zone==='trade'?'Operator Work Zone':'QuantaTrade desk'} →</a></div>
    </header>
    <p className="text-xs text-slate-400">Local operator workspace · Paperclip on port 3210 · Hosted multi-user access requires authenticated Paperclip memberships. Harness configuration and activation happen in Paperclip.</p>
    {error&&<div role="alert" className="p-4 border border-amber-600 rounded-xl text-amber-200">{error}<button onClick={refresh} className="ml-4 underline">Retry connection</button><p className="mt-2 text-xs">Start the local service: docker compose -p quanta-paperclip -f deploy/paperclip.compose.yml up -d</p></div>}
    {notice&&<p role="status" className="text-emerald-300">{notice}</p>}
    {state&&!state.company&&<section className={panel}><h2 className="text-xl font-bold">Create your {zone==='trade'?'trading desk':'operator'} organization</h2><p className="text-slate-400 my-3">Persistent Paperclip organization. Workers are added deliberately and start paused.</p><button className={button} disabled={busy} onClick={()=>act(()=>api.provision(zone),'Organization created.')}>Create organization</button></section>}
    {state?.company&&<><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Organization',state.company.name],['Workers',agents.length],['Tasks',state.tasks.length],['Reviews',state.reviews.length]].map(([label,value])=><div key={label} className={panel}><p className="text-xs text-slate-400">{label}</p><p className="text-xl font-bold mt-2">{value}</p></div>)}</div>
    <nav className="flex gap-2 flex-wrap">{['Workboard','Org chart','Onboarding','Training','Knowledge'].map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-4 py-3 ${tab===t?'bg-cyan-500/20 text-cyan-300 border border-cyan-600':'bg-slate-900 text-slate-400'}`}>{t}</button>)}<button onClick={exportWorkspace} className="ml-auto text-sm text-slate-400">Export workspace ↓</button></nav>
    {tab==='Workboard'&&<div className="grid md:grid-cols-2 gap-5"><section className={panel}><h2 className="text-xl font-bold mb-4">Create a reviewed work brief</h2><form className="space-y-3" onSubmit={e=>{e.preventDefault();void act(()=>api.task(zone,task),'Planning task saved to Paperclip backlog.');}}><input className={input} placeholder="Task title" required value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><textarea className={input} rows={5} placeholder="Goal, boundaries, deliverables and acceptance criteria" required value={task.description} onChange={e=>setTask({...task,description:e.target.value})}/><select className={input} value={task.agentId} onChange={e=>setTask({...task,agentId:e.target.value})}>{options}</select><button className={button} disabled={busy}>Save planning task</button></form><p className="text-xs text-slate-400 mt-3">Backlog tasks do not start workers. Human review is required. Handoffs and agent execution use Paperclip's native task system.</p></section><section className={panel}><h2 className="text-xl font-bold mb-4">Workboard</h2>{!state.tasks.length&&<p className="text-slate-400">No tasks yet.</p>}{state.tasks.map(t=><a key={t.id} href={`${state.consoleUrl}/issues/${t.identifier||t.id}`} target="_blank" rel="noreferrer" className="block border-b border-slate-800 py-4"><span className="text-xs text-cyan-400">{t.identifier} · {t.status}</span><h3>{t.title}</h3><p className="text-xs text-slate-500">{agents.find(a=>a.id===t.assigneeAgentId)?.name||'Unassigned'}</p></a>)}</section></div>}
    {tab==='Org chart'&&<section className={panel}><div className="text-center p-4 rounded-xl border border-orange-500 text-orange-300">Human operator · approvals & accountability</div><div className="grid md:grid-cols-3 gap-4 mt-6">{agents.map(a=><div key={a.id} className="rounded-xl border border-cyan-900 p-5"><p className="text-cyan-300 font-bold">{a.name}</p><p className="text-sm mt-2">{a.title||a.role}</p><p className="text-xs text-slate-400 mt-3">Reports to {agents.find(m=>m.id===a.reportsTo)?.name||'Human operator'}</p><p className="text-xs text-orange-300 mt-2">{a.adapterType} · {a.status}</p><p className="text-xs text-slate-500 mt-2">Monthly budget ${(a.budgetMonthlyCents/100).toFixed(2)}</p></div>)}</div>{!agents.length&&<p className="text-slate-400 mt-5">Onboard your first worker to build the reporting chart.</p>}<a href={state.links.org} target="_blank" rel="noreferrer" className="inline-block mt-5 text-cyan-300">Native org chart ↗</a></section>}
    {tab==='Onboarding'&&<section className={panel}><h2 className="text-xl font-bold">Name the worker. Define the job. Assign the harness.</h2>{identity&&<p className="text-sm text-cyan-300 mt-3">Identity handed off from the agent directory or Open House. Review the role and choose a runtime. No private knowledge or credentials were copied.</p>}<div className="flex gap-2 flex-wrap my-4">{templates[zone].map(([name,role])=><button key={name} className="border border-cyan-900 rounded-lg px-3 py-2 text-sm" onClick={()=>setWorker({...worker,name,role})}>{name}</button>)}</div><form className="grid md:grid-cols-2 gap-4" onSubmit={e=>{e.preventDefault();void act(()=>api.onboard(zone,worker),'Worker onboarded. Configure its harness and review it before activation.');}}><label>Name<input className={input} required value={worker.name} onChange={e=>setWorker({...worker,name:e.target.value})}/></label><label>Harness<select className={input} value={worker.adapterType} onChange={e=>setWorker({...worker,adapterType:e.target.value})}>{WORKER_HARNESSES.map(h=><option key={h}>{h}</option>)}</select></label><label className="md:col-span-2">Role & scope<textarea className={input} required value={worker.role} onChange={e=>setWorker({...worker,role:e.target.value})}/></label><label>Reports to<select className={input} value={worker.reportsTo} onChange={e=>setWorker({...worker,reportsTo:e.target.value})}>{options}</select></label><label>Monthly budget (USD)<input className={input} type="number" min="0" max="10000" step=".01" value={worker.budgetMonthlyCents/100} onChange={e=>setWorker({...worker,budgetMonthlyCents:Math.round(Number(e.target.value)*100)})}/></label><button className={button} disabled={busy}>Onboard paused worker</button></form><p className="text-xs text-slate-400 mt-4">Provider credentials, tool permissions and machine access require separate adapter setup. A selected harness is not a configured runtime. Company hire approvals are preserved.</p></section>}
    {tab==='Training'&&<div className="grid md:grid-cols-2 gap-5"><section className={panel}><h2 className="text-xl font-bold">Evidence-based training review</h2><p className="text-sm text-slate-400 my-3">Use Skill Studio to author and evaluate skills. Record the operator's review here; a review does not train model weights or activate a worker.</p><a className="text-cyan-300" href={state.links.training} target="_blank" rel="noreferrer">Paperclip Skill Studio ↗</a><form className="space-y-3 mt-5" onSubmit={e=>{e.preventDefault();void act(()=>api.review(zone,review),'Evaluation review recorded.');}}><select className={input} required value={review.agentId} onChange={e=>setReview({...review,agentId:e.target.value})}>{workerOptions}</select>{(['caseName','skillVersion','artifact','notes'] as const).map(k=><input key={k} className={input} required placeholder={{caseName:'Evaluation case',skillVersion:'Skill version',artifact:'Evidence file / run reference',notes:'Review findings'}[k]} value={review[k]} onChange={e=>setReview({...review,[k]:e.target.value})}/>)}<select className={input} value={review.verdict} onChange={e=>setReview({...review,verdict:e.target.value})}><option value="revise">Needs revision</option><option value="pass">Pass this evaluation</option></select><button className={button} disabled={busy}>Record review</button></form></section><section className={panel}>{state.reviews.slice().reverse().map(r=><article key={r.id} className="border-b border-slate-800 py-4"><h3>{r.caseName} · {r.verdict}</h3><p className="text-sm text-slate-400">{agents.find(a=>a.id===r.agentId)?.name} · {r.skillVersion} · {r.adapterType}</p><p className="my-2">{r.notes}</p><p className="text-xs text-cyan-400 break-all">{r.artifact}</p><time className="text-xs text-slate-500">{new Date(r.createdAt).toLocaleString()}</time></article>)}{!state.reviews.length&&<p className="text-slate-400">No evaluation reviews recorded.</p>}</section></div>}
    {tab==='Knowledge'&&<div className="grid md:grid-cols-2 gap-5"><section className={panel}><h2 className="text-xl font-bold">Private worker KB + master KB</h2><p className="text-sm text-slate-400 my-3">Notes stay in Quanta's local operator store. Master notes are explicitly shared. Private notes are not automatically copied into company tasks or harness prompts.</p><form className="space-y-3" onSubmit={e=>{e.preventDefault();void act(()=>api.knowledge(zone,note),'Knowledge note saved to selected scope.');}}><select className={input} value={note.agentId} onChange={e=>setNote({...note,agentId:e.target.value})}><option value="master">Shared master KB</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name} · private KB</option>)}</select><input className={input} required placeholder="Title" value={note.title} onChange={e=>setNote({...note,title:e.target.value})}/><textarea className={input} rows={5} required placeholder="Knowledge note" value={note.text} onChange={e=>setNote({...note,text:e.target.value})}/><input className={input} required placeholder="Source / provenance" value={note.source} onChange={e=>setNote({...note,source:e.target.value})}/><button className={button} disabled={busy}>Save knowledge</button></form></section><section className={panel}>{state.knowledge.filter(n=>n.agentId===note.agentId).map(n=><article key={n.id} className="border-b border-slate-800 py-4"><h3 className="text-cyan-300">{n.title}</h3><p className="whitespace-pre-wrap text-sm mt-2">{n.text}</p><p className="text-xs text-slate-500 mt-3">Source: {n.source}</p></article>)}{!state.knowledge.some(n=>n.agentId===note.agentId)&&<p className="text-slate-400">No notes in this scope yet.</p>}</section></div>}
    </>}
  </div>;
}
