import React, {useEffect,useState} from 'react';
import OperatorWorkZone from './OperatorWorkZone';
import GnoesisResearch from './GnoesisResearch';
import {researchService} from '../services/researchService';
import {workzoneService} from '../services/workzoneService';
import type {Run} from '../lib/research-contract';
import type {OperatorWorkZone as Workspace} from '../lib/workzone-contract';
export default function QuantaTrade(){
 const [tab,setTab]=useState('Desk'),[ticker,setTicker]=useState(''),[symbol,setSymbol]=useState(''),[runs,setRuns]=useState<Run[]>([]),[workspace,setWorkspace]=useState<Workspace|null>(null),[status,setStatus]=useState('Checking research engine…'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){const results=await Promise.allSettled([researchService.health(),researchService.runs(),workzoneService.state('trade')]);if(results[0].status==='fulfilled'){const h=results[0].value;setStatus(`Research engine: ${h.sidecar.status} · ${h.models.length} configured models`);}else setStatus('Research engine unavailable');if(results[1].status==='fulfilled')setRuns(results[1].value.runs);if(results[2].status==='fulfilled'){setWorkspace(results[2].value);setError('');}else setError(results[2].reason.message);}
 useEffect(()=>{void refresh();},[]);
 async function saveSymbols(symbols:string[]){setBusy(true);try{await workzoneService.watchlist(symbols);setSymbol('');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const ordered=runs.slice().sort((a,b)=>b.created_at.localeCompare(a.created_at));
 return <div className="space-y-6 pb-12"><header className="rounded-3xl border border-orange-500/40 bg-gradient-to-br from-indigo-950 via-slate-950 to-cyan-950 p-8 md:p-12"><p className="text-orange-400 font-bold text-xs tracking-[.3em] uppercase">QuantaTrade · SME Trading Desk</p><h1 className="text-4xl md:text-6xl font-bold mt-4">Evidence meets conviction.<br/><span className="text-cyan-300">Your desk. Your decision.</span></h1><p className="text-slate-300 max-w-2xl mt-5">Compose a desk of market specialists. Run evidence collection, bull and bear debate, risk review and portfolio research with an auditable decision journal.</p><div className="flex flex-wrap gap-3 mt-6">{['Evidence','SME debate','Risk review','Operator decision'].map((s,i)=><span key={s} className="border border-cyan-800 rounded-xl px-4 py-2 text-sm"><span className="text-orange-400 mr-2">0{i+1}</span>{s}</span>)}</div></header><div className="flex flex-wrap justify-between gap-3 text-xs text-slate-400"><span>{status}</span><span>Stock research · Human review · No broker execution</span></div><nav className="flex gap-2 flex-wrap">{['Desk','Research lab','Decision ledger','Evaluation','Digital workers'].map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-4 py-3 ${tab===t?'bg-cyan-500/20 border border-cyan-600 text-cyan-300':'bg-slate-900 text-slate-400'}`}>{t}</button>)}<a href="#/work-zone" className="ml-auto px-4 py-3 text-sm text-orange-300">Work Zone →</a></nav>
 {tab==='Digital workers'?<OperatorWorkZone zone="trade"/>:tab!=='Desk'?<GnoesisResearch key={`${tab}:${ticker}`} initialTab={tab==='Decision ledger'?'ledger':tab==='Evaluation'?'evaluation':'research'} initialTicker={ticker}/>:<>
 {error&&<p role="alert" className="rounded-xl border border-amber-800 p-4 text-amber-200">{error}<button className="ml-4 underline" onClick={refresh}>Retry</button></p>}
 <div className="grid lg:grid-cols-[1.2fr_1fr] gap-5"><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><h2 className="text-xl font-bold">Research watchlist</h2><p className="text-sm text-slate-400 my-3">Stored research findings, with timestamps. This is not a live quote feed.</p>{workspace?.company?<form className="flex gap-3 my-5" onSubmit={e=>{e.preventDefault();void saveSymbols([...workspace.watchlist,symbol.trim().toUpperCase()]);}}><input aria-label="Stock symbol" className="min-w-0 flex-1 bg-slate-950 border border-slate-700 rounded-xl p-3" required pattern="[A-Za-z][A-Za-z0-9.\-]{0,15}" placeholder="Stock symbol, e.g. AAPL" value={symbol} onChange={e=>setSymbol(e.target.value)}/><button disabled={busy} className="bg-gradient-to-r from-orange-500 to-amber-400 rounded-xl px-4 text-slate-950 font-bold">Add</button></form>:<button onClick={()=>setTab('Digital workers')} className="my-4 text-cyan-300 underline">Set up your desk organization to save a watchlist →</button>}
 {(workspace?.watchlist||[]).map(s=>{const run=ordered.find(r=>r.ticker===s);return <div key={s} className="border-t border-slate-800 py-4 flex items-center gap-3"><strong className="text-cyan-300 w-20">{s}</strong><div className="flex-1"><p className="text-sm">{run?`${run.status} · ${run.decision?.rating||'No decision'}`:'No research recorded'}</p>{run&&<p className="text-xs text-slate-500">As of {run.trade_date} · {new Date(run.updated_at).toLocaleString()}</p>}</div><button onClick={()=>{setTicker(s);setTab('Research lab');}} className="text-orange-300 text-sm">Research →</button><button aria-label={`Remove ${s}`} disabled={busy} onClick={()=>saveSymbols(workspace!.watchlist.filter(t=>t!==s))} className="text-slate-500">×</button></div>;})}
 </section><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><h2 className="text-xl font-bold">Latest research</h2>{!ordered.length&&<p className="text-slate-400 my-4">No stored research runs. Open Research lab to review model configuration and a run budget.</p>}{ordered.slice(0,6).map(r=><button key={r.id} onClick={()=>{setTicker(r.ticker);setTab('Decision ledger');}} className="w-full text-left border-b border-slate-800 py-4"><p className="text-cyan-300">{r.ticker} <span className="text-slate-400 text-xs">{r.status} · {r.trade_date}</span></p><p className="text-sm mt-2">{r.decision?.executive_summary||r.error?.message||'No decision available'}</p><p className="text-xs text-slate-500 mt-2">{r.usage.calls} model calls · {r.usage.cost_usd===null?'Cost unavailable':`$${r.usage.cost_usd.toFixed(4)}`}</p></button>)}</section></div>
 <section className="rounded-2xl border border-cyan-900 p-6"><h2 className="text-xl font-bold">Desk operating model</h2><p className="text-slate-400 text-sm mt-3">Desk lead → market, news, fundamentals & social analysts → bull / bear debate → risk committee → portfolio research → human decision. Evidence, assumptions and disagreement remain in the research journal. Paperclip manages worker roles and work briefs; research runs use Quanta's existing research engine.</p><p className="text-xs text-orange-300 mt-4">Predictive value is unvalidated. Evaluation records are not an execution backtest. No trades are submitted.</p></section></>}
 </div>;
}
